apiVersion: v1
kind: ConfigMap
metadata:
  name: progress-config
data:
  PORT: "3002"
  NODE_ENV: "production"
  DB_HOST: "10.178.0.33"
  DB_PORT: "3306"
  DB_NAME: "progress_db"
  DB_USER: "root"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  LEARNING_SERVICE_URL: "http://learning-service:3000"
